# Generated by Django 3.2.5 on 2021-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('image', models.URLField(blank=True, default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default=None, max_length=1000)),
            ],
        ),
    ]
