# Generated by Django 3.2.5 on 2021-07-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='hashtags', to='hashtags.Hashtag'),
        ),
    ]
